version: "3.3"
services:
  product:
    container_name: ecomm-product
    build: ./product
  account:
    container_name: ecomm-account
    build: ./account
  mongo:
    container_name: mongo-ecomm
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
  
  mysql:
    container_name: mysql-ecomm
    image: mysql
    restart: always
    volumes:
      - ecomm-mysql-volume:/var/lib/mysql
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret
  
volumes:
  ecomm-mysql-volume:
    external: true