openapi: 3.0.3
info:
  title: API de contas
  version: 0.0.1
  license:
    name: "Licença: GPLv3"
    url: https://www.gnu.org/licenses/gpl-3.0.html
externalDocs:
  description: Documentação burocrática
  url: https://mockapi.io


paths:
  /api/admin/users:
    get:
      summary: Lista todos os usuários
      responses: 
        200:
          description: Sucesso, retorna todas os usuários
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users"
        404:
          description: Sem usuários cadastrados
  /api/users/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    get:
      summary: Encontra o usuário
      responses: 
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        401:
          description: Usuário não autorizado
        404:
          description: Usuário ou API não encontrados
          
  /api/admin/users/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    post:
      security:
      - auth: []
      summary: Cria novo Usuárop
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        201:
          description: Usuário cadastrado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        401:
          description: Usuário não autorizado
        404:
          description: Usuário ou API não encontrados
    put:
      security:
      - auth: []
      summary: Atualiza o usuário
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        201:
          description: Usuário atualizado
        401:
          description: Usuário não autorizado
        404:
          description: Usuário não encontrado
    delete:
      security:
      - auth: []
      summary: Deleta o usuário
      responses:
        200:
          description: Usuário deletado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        401:
          description: Usuário não autorizado
        404:
          description: Usuário não encontrado
    
components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: string
        nome:
          type: string
        cpf:
          type: string
        telefone:
          type: string
        endereco:
          type: object
          properties:
            rua:
              type: string
            numero:
              type: string
            complemento:
              type: string
            cep:
              type: string
            cidade:
              type: string
            estado:
              type: string
        
    users:
        type: array
        items:
          $ref: "#/components/schemas/user"
    

  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
         
      
